#include "localdbmanager.h"
#include "config/client_config.h"
#include <QDebug>
#include <QFile>
#include <QCoreApplication>

LocalDBManager* LocalDBManager::m_instance = nullptr;

LocalDBManager::LocalDBManager(QObject *parent)
    : QObject(parent)
    , m_db(nullptr)
{
}

LocalDBManager::~LocalDBManager()
{
    closeDatabase();
}

LocalDBManager* LocalDBManager::getInstance()
{
    if(m_instance == nullptr)
    {
        m_instance = new LocalDBManager();
    }
    return m_instance;
}

void LocalDBManager::setClientId(const QString& clientId)
{
    QMutexLocker locker(&m_mutex);
    m_clientId = clientId;
    qDebug() << "Local database client_id set to:" << clientId;
}

bool LocalDBManager::initDatabase()
{
    QMutexLocker locker(&m_mutex);

    if(m_clientId.isEmpty())
    {
        m_clientId = ClientConfig::getInstance()->getClientId();
    }

    QString dbPath = QString("%1/%2_data.db")
                         .arg(QCoreApplication::applicationDirPath())
                         .arg(m_clientId);
    qDebug() << "Initializing local database:" << dbPath;

    int ret = sqlite3_open(dbPath.toUtf8().constData(), &m_db);
    if(ret != SQLITE_OK)
    {
        qDebug() << "Failed to open local database:" << sqlite3_errmsg(m_db);
        return false;
    }

    qDebug() << "Local database opened successfully";
    return createTables();
}

void LocalDBManager::closeDatabase()
{
    QMutexLocker locker(&m_mutex);
    if(m_db != nullptr)
    {
        sqlite3_close(m_db);
        m_db = nullptr;
    }
}

bool LocalDBManager::createTables()
{
    char* errMsg = nullptr;
    const char* sql = R"(
        CREATE TABLE IF NOT EXISTS goods (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            price REAL NOT NULL DEFAULT 0,
            unit TEXT NOT NULL DEFAULT '',
            stock INTEGER NOT NULL DEFAULT 0,
            create_time INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
        );
    )";

    int ret = sqlite3_exec(m_db, sql, nullptr, nullptr, &errMsg);
    if(ret != SQLITE_OK)
    {
        qDebug() << "Failed to create goods table:" << errMsg;
        sqlite3_free(errMsg);
        return false;
    }

    qDebug() << "Goods table created/checked successfully";
    return true;
}

/**
 * @brief Add a new goods record to the goods table
 * The purpose is to prevent the data you pass in from being compiled into instructions that cause errors
 */
int LocalDBManager::addGoods(const QString& name, float price, const QString& unit, int stock)
{
    // Mutex lock to ensure serialized multi-threaded database access, avoiding concurrency conflicts
    QMutexLocker locker(&m_mutex);

    // prepare -> bind -> step -> finalize standard prepared statement execution flow
    // Define the INSERT SQL; ? is a placeholder, filled with dynamic data via binding
    const char* sql = "INSERT INTO goods (name, price, unit, stock) VALUES (?, ?, ?, ?);";
    // Declare prepared statement handle, initialize to null to avoid wild pointer
    sqlite3_stmt* stmt = nullptr;

    // Compile the SQL, generate the prepared execution object
    // m_db: database connection handle; sql: SQL to compile; -1: auto-compute SQL length; &stmt: output prepared handle; nullptr: ignore remaining SQL
    int ret = sqlite3_prepare_v2(m_db, sql, -1, &stmt, nullptr);  //In plain words: parse and compile text SQL into a fixed statement template, stored in stmt.
    // Check whether SQL compilation succeeded
    if(ret != SQLITE_OK)
    {
        // Compilation failed; print the database error message
        qDebug() << "Add goods prepare statement failed:" << sqlite3_errmsg(m_db);
        return -1;
    }

    // Bind placeholder #1: goods name (text)
    // Index starts at 1; convert to UTF-8 to match SQLite encoding; SQLITE_TRANSIENT means SQLite copies the temporary string
    sqlite3_bind_text(stmt, 1, name.toUtf8().constData(), -1, SQLITE_TRANSIENT);
    // Bind placeholder #2: goods price (floating point)
    sqlite3_bind_double(stmt, 2, price);
    sqlite3_bind_text(stmt, 3, unit.toUtf8().constData(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_int(stmt, 4, stock);

    // Execute the compiled, parameter-bound SQL statement
    ret = sqlite3_step(stmt);
    // Free the prepared statement resource; pairs with sqlite3_prepare_v2 to avoid memory leak
    sqlite3_finalize(stmt);

    // SQL execution result check; for INSERT/DELETE/UPDATE statements, SQLITE_DONE is returned on success
    if(ret != SQLITE_DONE)
    {
        qDebug() << "Add goods failed:" << sqlite3_errmsg(m_db);
        return -1;
    }

    // Get the auto-increment primary key ID generated by the last INSERT in the current connection
    int newId = (int)sqlite3_last_insert_rowid(m_db);
    qDebug() << "Goods added successfully, ID:" << newId;
    return newId;
}

int LocalDBManager::updateGoods(int id, const QString& name, float price, const QString& unit, int stock)
{
    QMutexLocker locker(&m_mutex);

    const char* sql = "UPDATE goods SET name=?, price=?, unit=?, stock=? WHERE id=?;";
    sqlite3_stmt* stmt = nullptr;
    int ret = sqlite3_prepare_v2(m_db, sql, -1, &stmt, nullptr);
    if(ret != SQLITE_OK)
    {
        qDebug() << "Update goods prepare statement failed:" << sqlite3_errmsg(m_db);
        return -1;
    }

    sqlite3_bind_text(stmt, 1, name.toUtf8().constData(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_double(stmt, 2, price);
    sqlite3_bind_text(stmt, 3, unit.toUtf8().constData(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_int(stmt, 4, stock);
    sqlite3_bind_int(stmt, 5, id);

    ret = sqlite3_step(stmt);
    sqlite3_finalize(stmt);

    if(ret != SQLITE_DONE)
    {
        qDebug() << "Update goods failed:" << sqlite3_errmsg(m_db);
        return -1;
    }

    return 0;
}

int LocalDBManager::deleteGoods(int id)
{
    QMutexLocker locker(&m_mutex);

    const char* sql = "DELETE FROM goods WHERE id=?;";
    sqlite3_stmt* stmt = nullptr;
    int ret = sqlite3_prepare_v2(m_db, sql, -1, &stmt, nullptr);
    if(ret != SQLITE_OK)
    {
        qDebug() << "Delete goods prepare statement failed:" << sqlite3_errmsg(m_db);
        return -1;
    }

    sqlite3_bind_int(stmt, 1, id);

    ret = sqlite3_step(stmt);
    sqlite3_finalize(stmt);

    if(ret != SQLITE_DONE)
    {
        qDebug() << "Delete goods failed:" << sqlite3_errmsg(m_db);
        return -1;
    }

    return 0;
}

/**
 * @brief Query a single goods record by goods ID
 * @param id Goods primary key ID to query
 * @param goods Output parameter; on success, the goods data is stored in this struct
 * @return int Result: 0 success; -1 SQL compilation failure or no matching data
 * @note Multi-threaded database access is mutex-locked for concurrency safety
 */
int LocalDBManager::queryGoodsById(int id, goods_info_t* goods)
{
    // Mutex lock; under multi-threading, serialize database operations to prevent concurrency conflicts
    QMutexLocker locker(&m_mutex);

    // Define char array to hold the assembled SQL
    char sql[256] = {0};
    // Format and assemble the SELECT SQL; query all goods fields by ID condition
    snprintf(sql, sizeof(sql), "SELECT id, name, price, unit, stock, create_time FROM goods WHERE id=%d;", id);

    // Declare prepared statement handle, initially null to avoid wild pointer
    sqlite3_stmt* stmt = nullptr;
    // Pre-compile the SQL, generate the execution template and store in stmt
    int ret = sqlite3_prepare_v2(m_db, sql, -1, &stmt, nullptr);
    // Check whether SQL pre-compilation failed; return directly on failure
    if(ret != SQLITE_OK)
    {
        return -1;
    }

    // Execute the query statement; SQLITE_ROW indicates a valid row was read
    if(sqlite3_step(stmt) == SQLITE_ROW)
    {
        // Read column #0: goods ID (integer)
        goods->id = sqlite3_column_int(stmt, 0);
        // Read column #1: goods name (text); copy the string, reserving one byte for the null terminator
        strncpy(goods->name, (const char*)sqlite3_column_text(stmt, 1), sizeof(goods->name)-1);
        // Read column #2: goods price (floating point)
        goods->price = sqlite3_column_double(stmt, 2);
        // Read column #3: goods unit (text); copy the string, reserving one byte for the null terminator
        strncpy(goods->unit, (const char*)sqlite3_column_text(stmt, 3), sizeof(goods->unit)-1);
        // Read column #4: goods stock (integer)
        goods->stock = sqlite3_column_int(stmt, 4);
        // Read column #5: creation timestamp (integer)
        goods->create_time = sqlite3_column_int(stmt, 5);

        // Free the prepared statement resource, prevent memory leak
        sqlite3_finalize(stmt);
        return 0;
    }

    // No matching data found; free the prepared statement resource
    sqlite3_finalize(stmt);
    return -1;
}

int LocalDBManager::queryAllGoods(QList<goods_info_t>* goodsList)
{
    QMutexLocker locker(&m_mutex);

    const char* sql = "SELECT id, name, price, unit, stock, create_time FROM goods ORDER BY id;";
    sqlite3_stmt* stmt = nullptr;
    int ret = sqlite3_prepare_v2(m_db, sql, -1, &stmt, nullptr);
    if(ret != SQLITE_OK)
    {
        return -1;
    }

    goodsList->clear();
    while(sqlite3_step(stmt) == SQLITE_ROW)
    {
        goods_info_t goods;
        memset(&goods, 0, sizeof(goods_info_t));
        goods.id = sqlite3_column_int(stmt, 0);
        strncpy(goods.name, (const char*)sqlite3_column_text(stmt, 1), sizeof(goods.name)-1);
        goods.price = sqlite3_column_double(stmt, 2);
        strncpy(goods.unit, (const char*)sqlite3_column_text(stmt, 3), sizeof(goods.unit)-1);
        goods.stock = sqlite3_column_int(stmt, 4);
        goods.create_time = sqlite3_column_int(stmt, 5);
        goodsList->append(goods);
    }

    sqlite3_finalize(stmt);
    return 0;
}

int LocalDBManager::deductStock(int id, int quantity)
{
    QMutexLocker locker(&m_mutex);

    char sql[256] = {0};
    snprintf(sql, sizeof(sql),
        "UPDATE goods SET stock = stock - %d WHERE id=%d AND stock >= %d;",
        quantity, id, quantity);

    char* errMsg = nullptr;
    int ret = sqlite3_exec(m_db, sql, nullptr, nullptr, &errMsg);
    if(ret != SQLITE_OK)
    {
        qDebug() << "Deduct stock failed:" << errMsg;
        sqlite3_free(errMsg);
        return -1;
    }

    if(sqlite3_changes(m_db) == 0)
    {
        qDebug() << "Insufficient stock or goods does not exist, ID:" << id;
        return -1;
    }

    return 0;
}

int LocalDBManager::addStock(int id, int quantity)
{
    QMutexLocker locker(&m_mutex);

    char sql[256] = {0};
    snprintf(sql, sizeof(sql),
        "UPDATE goods SET stock = stock + %d WHERE id=%d;",
        quantity, id);

    char* errMsg = nullptr;
    int ret = sqlite3_exec(m_db, sql, nullptr, nullptr, &errMsg);
    if(ret != SQLITE_OK)
    {
        qDebug() << "Add stock failed:" << errMsg;
        sqlite3_free(errMsg);
        return -1;
    }

    return 0;
}
